# GrabCheck.srv
# This service defines the communication format for detecting object grab

---
# Service response
# returns information about the success of the operation and any relevant messages
bool object_detected
