# MoveToGrid.srv
# This service defines the communication format for moving the arm to a grid cell
#Service request
int32 box_id

---
#Service response
# returns information about the success of the operation and any relevant messages
bool success
string message
