# ServoOff.srv
# This service defines the communication format for the servos
# service request

---
# Service response
# returns information about the success of the operation and any relevant messages
bool success